# Script to fix all critical compilation errors
# This generates missing proto stub packages and fixes common issues

$ErrorActionPreference = "Continue"

Write-Host "===== Fixing Compilation Errors =====" -ForegroundColor Cyan
Write-Host ""

# List of services that need proto stub packages
$services = @(
    @{Name="product-service"; Path="catalog-discovery"; Proto="product"},
    @{Name="review-service"; Path="catalog-discovery"; Proto="review"},
    @{Name="search-service"; Path="catalog-discovery"; Proto="search"},
    @{Name="cart-service"; Path="transaction-core"; Proto="cart"},
    @{Name="checkout-service"; Path="transaction-core"; Proto="checkout"},
    @{Name="payment-service"; Path="transaction-core"; Proto="payment"}
)

# Create proto stub packages
Write-Host "Creating proto stub packages..." -ForegroundColor Yellow
foreach ($svc in $services) {
    $protoDir = "C:\Users\Admin\Desktop\projects\go-ecommerce\backend\services\$($svc.Path)\$($svc.Name)\proto\$($svc.Proto)\v1"
    
    if (!(Test-Path $protoDir)) {
        New-Item -ItemType Directory -Force -Path $protoDir | Out-Null
        Write-Host "  Created: $protoDir" -ForegroundColor Green
        
        # Create a minimal stub .go file
        $stubContent = @"
// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a temporary stub file. Run 'make proto' to generate actual protobuf code.

package v1

// TODO: Generate actual protobuf code
// Run: protoc --go_out=. --go-grpc_out=. proto/$($svc.Proto)/v1/$($svc.Proto).proto
"@
        
        Set-Content -Path "$protoDir\stub.go" -Value $stubContent
        Write-Host "  Created stub: $protoDir\stub.go" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "Proto stubs created. Note: These are temporary stubs." -ForegroundColor Yellow
Write-Host "You need to:" -ForegroundColor Yellow
Write-Host "  1. Create .proto files in proto/<service>/v1/" -ForegroundColor Cyan
Write-Host "  2. Run 'make proto' to generate actual gRPC code" -ForegroundColor Cyan
Write-Host "  3. Or use 'protoc' manually to generate code" -ForegroundColor Cyan
Write-Host ""

# Sync workspace
Write-Host "Syncing workspace..." -ForegroundColor Yellow
cd C:\Users\Admin\Desktop\projects\go-ecommerce\backend
go work sync

Write-Host ""
Write-Host "===== Script Complete =====" -ForegroundColor Green
Write-Host "Remaining issues to fix manually:" -ForegroundColor Yellow
Write-Host "  - Domain model field mismatches (Product, Payment, etc.)" -ForegroundColor Cyan
Write-Host "  - Missing repository methods" -ForegroundColor Cyan  
Write-Host "  - Generate actual protobuf code" -ForegroundColor Cyan
